apiVersion: v1
kind: ConfigMap
metadata:
  name: laravel-conf
data:
  APP_NAME: "librarika"
  APP_ENV: "production"
  APP_DEBUG: "false"
  APP_TIMEZONE: "Asia/Jakarta"
  APP_URL: "https://www.127.0.0.1.nip.io"
  APP_LOCALE: "id"
  APP_FALLBACK_LOCALE: "en"
  APP_FAKER_LOCALE: "id_ID"
  APP_MAINTENANCE_DRIVER: "file"
  APP_MAINTENANCE_STORE: "database"
  APP_TRUSTED_HOSTS: "https://www.127.0.0.1.nip.io"
  LOG_CHANNEL: "stderr"
  LOG_STACK: "single"
  LOG_DEPRECATIONS_CHANNEL: "null"
  LOG_LEVEL: "info"
  DB_CONNECTION: "mysql"
  DB_HOST: "librarika-mysql"
  DB_PORT: "3306"
  SESSION_DRIVER: "database"
  SESSION_LIFETIME: "120"
  SESSION_ENCRYPT: "false"
  SESSION_PATH: "/"
  SESSION_DOMAIN: "null"
  BROADCAST_CONNECTION: "log"
  FILESYSTEM_DISK: "local"
  QUEUE_CONNECTION: "database"
  CACHE_STORE: "database"
  CACHE_PREFIX: ""
  MEMCACHED_HOST: "127.0.0.1"
  REDIS_HOST: "127.0.0.1"
  REDIS_PORT: "6379"
  MAIL_MAILER: "smtp"
  MAIL_HOST: "sandbox.smtp.mailtrap.io"
  MAIL_PORT: "2525"
  MAIL_ENCRYPTION: "null"
  MAIL_FROM_ADDRESS: "librarika@example.com"
  MAIL_FROM_NAME: "librarika-fpm-service"
  AWS_DEFAULT_REGION: "us-east-1"
  AWS_BUCKET: ""
  AWS_USE_PATH_STYLE_ENDPOINT: "false"
  VITE_APP_NAME: "${APP_NAME}"