apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: librarika-app
spec:
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: librarika-fpm
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: backend
      layer: fpm
  template:
    metadata:
      labels:
        app: librarika-fpm
        tier: backend
        layer: fpm
    spec:
      initContainers:
        - name: librarika-fpm-migration
          image: ghcr.io/alvianto21/ghcr.io/librarika_fpm:master
          imagePullPolicy: IfNotPresent
          command:
            - php
          args:
            - artisan
            - migrate
            - --force
          envFrom:
            - configMapRef:
                name: laravel-conf
            - secretRef:
                name: laravel-credential-conf
      containers:
      - name: librarika-fpm
        image: ghcr.io/alvianto21/ghcr.io/librarika_fpm:master
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            cpu: "1000m"
            memory: "3000Mi"
        ports:
        - containerPort: 9000
        envFrom:
          - configMapRef:
              name: laravel-conf
          - secretRef:
              name: laravel-credential-conf
        volumeMounts:
          - mountPath: /var/www/html/storage/app/public
            name: librarika-storage
            subPath: public
      volumes:
        - name: librarika-storage
          persistentVolumeClaim:
            claimName: librarika-app

---
apiVersion: v1
kind: Service
metadata:
  name: librarika-fpm-service
spec:
  selector:
    tier: backend
    layer: fpm
  ports:
  - port: 9000
    targetPort: 9000
    protocol: TCP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: librarika-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: backend
      layer: web-server
  template:
    metadata:
      labels:
        app: librarika-nginx
        tier: backend
        layer: web-server
    spec:
      containers:
      - name: librarika-nginx
        image: ghcr.io/alvianto21/ghcr.io/librarika_nginx:master
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "1Gi"
            cpu: "400m"
          requests:
            memory: "128Mi"
            cpu: "150m"
        ports:
        - containerPort: 80
        env:
          - name: FPM_HOST
            value: librarika-fpm-service:9000
        volumeMounts:
          - mountPath: /var/www/html/public/storage
            name: librarika-storage
            subPath: public
      volumes:
        - name: librarika-storage
          persistentVolumeClaim:
            claimName: librarika-app

---
apiVersion: v1
kind: Service
metadata:
  name: librarika-nginx-service
spec:
  selector:
    tier: backend
    layer: web-server
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: laravel-nginx
  labels:
    app.kubernetes.io/name: laravel-nginx
  annotations:
    # nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
spec:
  ingressClassName: nginx
  # tls:
  #   - hosts:
  #     - librarika.local.com
  #     secretName: librarika-test-tls
  rules:
  - host: www.127.0.0.1.nip.io
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: librarika-nginx-service
            port: 
              number: 80
